### ISSUE TITLE
FeatureCollection and XMLFormatter

### ISSUE THREAD

**Issue by juliusfriedman** [NetTopologySuite/NetTopologySuite.Features#13]
`IFeatureCollection` does not support `Add(Object)` so it's not easily used by the `XmlSerializer`.

1) Are there any examples of using the `XmlSerializer` with `IFeatureCollection` 

2) If not how would one easily go about providing a general sterilizer if `IFeatureCollection` does not support `Add(Object)`...

The easiest thing I can think of at the current time is to serialize to use GML

**Comment by FObermaier** [comment]
FeatureCollection does not work with XmlSerializer because it is derived from `Collection<IFeature>`. The XmlSerializer won't work with the `IFeature` interface without `FeatureCollection` implementing `IXmlSerialzable`. 

If we did that, we'd have to implement `IXmlSerializable` in our `Feature` class, too.

Given that this issue is 2,5 years old without any additional support, we'll leave the library as is.
